version: 2.1

jobs:
  mabl_test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Run Mabl Tests
          command: |
            npm install -g @mablhq/mabl-cli
            mabl login --api-key RgYhOfX3bSVXo8VweVZ7GQ
            mabl tests run --environment-id <your-environment-id>

workflows:
  version: 2
  mabl_test_workflow:
    jobs:
      - mabl_test